apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-db-pvc
  namespace: glpi
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glpi-data-pvc
  namespace: glpi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
